src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from notebook.views import home_screen_view
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticated_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('notebook/', include('notebook.urls', 'notebook')),   #powiązanie z notebook.ulrs
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('must_authenticated/', must_authenticated_view, name='must_authenticated'),



]

src/notebook/urls.py
from django.urls import path
from notebook.views import (
    create_blog_view,
    detail_blog_post,

)

app_name = 'notebook'

urlpatterns = [
    path('create/', create_blog_view, name='create'),
    path('detail/', detail_blog_post, name='detail'), #slug !!!!! pokombinowac ze slugiem bo inaczej nie wywietli więcej niż dwa posty

]

src/notebook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','draft'),
        ('published','published')
    )
    author = models.ForeignKey('account.Account', on_delete=models.CASCADE, related_name='blog_post')
    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    slug  = models.SlugField(blank=True, unique_for_date=publish) #slug to url, unique_for_date=publish-bud adresów wg daty publikacji

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Nowy post'
        verbose_name_plural = 'Posty'

    def __str__(self):
        return self.title

src/notebook/forms.py
from django import forms
from notebook.models import Post


class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body']

src/notebook/views.py
from django.shortcuts import render, redirect, get_object_or_404
from notebook.models import Post
from notebook.forms import CreatePostForm
from account.models import Account
from notebook.models import Post


# def create_blog_view(request):
#     context = {}
#     user = request.user
#     if not user.is_authenticated:
#         return redirect('must_authenticated')
#     form = CreatePostForm(request.POST)
#     if form.is_valid():
#         form.save()
#         author = Account.objects.filter(email=user.email).first()
#         author.save()
#         form = CreatePostForm()
#     context['form'] = form
#     return render(request, 'notebook/create_blog.html', context)

def home_screen_view(request):
    context = {}
    blog_posts = Post.objects.all()
    context['blog_posts'] = blog_posts
    return render(request, 'notebook/home.html', context)


def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticated')
    form = CreatePostForm(request.POST)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreatePostForm()
    context['form'] = form
    return render(request, 'notebook/create_blog.html', context)


def detail_blog_post(request):
    context = {}
    blog_post = get_object_or_404(Post)
    context['blog_post'] = blog_post
    return render(request, 'notebook/detail_blog.html', context)

src/notebook/templates/notebook/create_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post">
                {% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label>Title</label>
					<input class="form-control" type="text" name="title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>
		</div>
	</div>
</div>



{% endblock content %}



<!--<div class="container">-->
<!--	<div class="row">-->
<!--		<div class="col-lg-7 offset-lg-1">-->
<!--			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}-->

<!--				&lt;!&ndash; title &ndash;&gt;-->
<!--				<div class="form-group">-->
<!--					<label for="id_title">Title</label>-->
<!--					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>-->
<!--				</div>-->

<!--				&lt;!&ndash; Body &ndash;&gt;-->
<!--				<div class="form-group">-->
<!--					<label for="id_body">Content</label>-->
<!--					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>-->
<!--				</div>-->

<!--				&lt;!&ndash; Image &ndash;&gt;-->
<!--				<div class="form-group">-->
<!--					<label for="id_image">Image</label>-->
<!--					<input  type="file" name="image" id="id_image" accept="image/*" required>-->
<!--				</div>-->

<!--				&lt;!&ndash; Submit btn &ndash;&gt;-->
<!--				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>-->
<!--			</form>	-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->

src/notebook/templates/notebook/detail_blog.html
{% extends 'base.html' %}

{% block content %}



<style>


    .container{
        padding:20px;
    }

    .card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}

</style>
<!-- Blog Post -->
<div class="card m-auto">
    <div class="row">
        <div class="card m-auto">
            <div class="card-body mt-2 mb-2">
                <p>blog_detail</p>
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body}}</p>

            <div class="card-footer">
                Updated {{blog_post.created}} by {{blog_post.author}}
            </div>



                <p>zrobić blog_post_edit + możliwość dodawania zdjęć + slug aby można bylo dodać osobne posty lub zrobić petle</p>

        </div>
    </div>

</div>
<!-- End Blog Post -->
{% endblock content %}

src/notebook/templates/notebook/home.html
{% extends 'base.html' %}

{% block content %}


<style type="text/css">

	@media (max-width: 768px) {
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) {
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>

<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<p class="lead">Notebook.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'notebook:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'notebook/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'notebook/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->


		</div>
		<!-- end blog feed -->



{% endblock content %}